version: "3.9"

services:
  db:
    build: ./requirements/mariadb
    container_name: db
    env_file: .env
    volumes:
      - $HOST_PATH_DB:/var/lib/mysql
    networks:
      - docker-network
  
  wordpress:
    depends_on:
      - db
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_ADMIN=$MYSQL_ADMIN
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD_ADMIN=$MYSQL_PASSWORD_ADMIN
      - WORDPRESS_DB_PASSWORD_USER=$MYSQL_PASSWORD_USER
      - WORDPRESS_DB_HOST=db:3306
    volumes:
       - $HOST_PATH_WORDPRESS:$WORDPRESS_DIR
    networks:
      - docker-network
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    env_file: .env
    container_name: nginx
    ports:
      - "443:443"
    volumes:
       - $HOST_PATH_WORDPRESS:$WORDPRESS_DIR
    networks:
      - docker-network
    restart: unless-stopped
      
networks:
  docker-network:
    driver: bridge
